---
title: "Lab 06 - Functions and iterations"
author: "Ben Calder"
date: "`r Sys.Date()`"
output: html_document
---


### Packages and Data

```{r load-packages, message=FALSE}
library(tidyverse) 
library(ggplot2)
```

```{r diamon_rename}
diamonds <- diamonds %>% rename(
    depth_pct = depth,
    length_mm = x,
    width_mm = y,
    depth_mm = z,
    table_pct = table
  )
```


## Exercise 1

```{r}
# Do some preliminary investigations & cleaning

diamonds %>% select('depth_pct','length_mm','width_mm','depth_mm',)

ggplot()


```


## Exercise 2

```{r}

diamonds <- diamonds %>%
  mutate(table_mm = table_pct * width_mm / 100)

# Overall table_mm arithmetic mean?


diamonds %>% summarise(mean(table_mm))



# table_mm arithmetic mean within each clarity category


diamonds %>% group_by(clarity) %>% summarise(mean(table_mm))



```

_the greater the length of the diamond the worse the clarity of the diamond_

## Exercise 3

_Do derivation on paper, unless you know how to write LaTeX code_


## Exercise 4

```{r}
# Write gmean() command

gmean <- function(x) {
  exp(mean(log(x)))
}

```

## Exercise 5

```{r, error = TRUE}

test_data <- list(
  test1 = c(2.1, 3.8, 4.2),
  test2 = c(1, 10, 100, 1000),
  test3 = c(0, 1, 4),
)


# Create for loop to test gmean() on the above examples

for (x in test_data[x]) {
  gmean(x)
}

```


## Exercise 6

```{r}
# Copy gmean() from Ex4 and edit it to check the input





# Copy your code from Ex 5 to test your new command





```


## Exercise 7

```{r}
# Overall table_mm geometic mean?






# table_mm geometic mean within each clarity category






```

_Add your comment here_


## Exercise 8 (optional)

```{r}
# Create gmean2() that computes the geometric mean 
#   that uses the original definition






```


## Exercise 9 (optional)

```{r}
# Create a function that computes the harmonic mean







```
